### ISSUE TITLE
question regarding varscan cnv file as input absCNseq

### ISSUE THREAD

**Issue by kylec** [raylim/scripts#1]
I am wondering if you are using the .call or .copynumber output generated from varcan2 and smoothed by dnacopy as input to absCNseq.

**Comment by raylim** [comment]
It¹s the output from segmentCNV2.R which uses CGHcall.

Raymond

From:  kylec notifications@github.com
Reply-To:  raylim/scripts
<reply+i-30551518-cb7d713ffe88321497dea0adfd98c873fe06f118-3074310@reply.git
hub.com>
Date:  Monday, March 31, 2014 at 5:31 PM
To:  raylim/scripts scripts@noreply.github.com
Subject:  [scripts] question regarding varscan cnv file as input absCNseq
(#1)

I am wondering if you are using the .call or .copynumber output generated
from varcan2 and smoothed by dnacopy as input to absCNseq.

‹
Reply to this email directly or view it on GitHub
https://github.com/raylim/scripts/issues/1 .
